language: node_js
script:
  echo "TODO: implement eslint for ci"
deploy:
  provider: npm
  user: oscm@edx.org
  api_key:
    secure: <HELP ME, FEANIL>
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^npmv[0-9]+\.[0-9]+\.[0-9]+$
